# Generated by Django 5.2.5 on 2025-10-15 18:13

from django.db import models, migrations
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        # Delete old tables
        migrations.RunSQL("DROP TABLE IF EXISTS society_family;"),
        migrations.RunSQL("DROP TABLE IF EXISTS society_event;"),
        migrations.RunSQL("DROP TABLE IF EXISTS society_member;"),
        
        # Create new tables
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('house_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='society.area')),
            ],
        ),
        migrations.CreateModel(
            name='SubCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.CharField(db_index=True, max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcollections', to='society.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('adhar', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\d{12}$')])),
                ('status', models.CharField(choices=[('live', 'Live'), ('dead', 'Dead'), ('terminated', 'Terminated')], db_index=True, default='live', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_surname', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_surname', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_father', to='society.member')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='society.house')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_as_mother', to='society.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberObligation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partial')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(db_index=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='society.area')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='society.member')),
                ('subcollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='society.subcollection')),
            ],
        ),
        migrations.AddIndex(
            model_name='memberobligation',
            index=models.Index(fields=['subcollection', 'paid_status'], name='society_mem_subcoll_7f8b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberobligation',
            index=models.Index(fields=['member', 'subcollection'], name='society_mem_member_b0c8a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='subcollection',
            constraint=models.UniqueConstraint(fields=('collection', 'year'), name='society_sub_collection_7f3b5a_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberobligation',
            constraint=models.UniqueConstraint(fields=('subcollection', 'member'), name='society_mem_subcoll_8f3b5a_idx'),
        ),
    ]
