# Generated by Django 5.2.5 on 2025-10-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_auto_20251015_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default='Unknown Member', max_length=100),
            preserve_default=False,
        ),
    ]