# Generated by Django 5.2.5 on 2026-01-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_recentaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='firebase_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='firebase_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
