# Generated by Django 5.2.5 on 2026-01-08 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_house_firebase_id_member_firebase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='adhar',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', message='Enter the last 4 digits of Aadhaar')]),
        ),
    ]
