# Generated by Django 5.2.5 on 2026-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_appsettings_firebase_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='grandfather_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
