# Generated by Django 5.2.5 on 2026-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0011_house_locality_member_grandfather_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('firebase_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
