# Generated by Django 5.2.5 on 2026-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0012_digitalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='google_drive_client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='google_drive_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='google_drive_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='google_drive_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
