# Generated by Django 5.2.5 on 2026-02-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0013_appsettings_google_drive_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='second_spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_spouse_reverse', to='society.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='second_spouse_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='second_spouse_surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
