# Generated by Django 5.2.5 on 2026-03-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0014_member_second_spouse_member_second_spouse_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentAction',
        ),
        migrations.AddField(
            model_name='house',
            name='sync_pending',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sync_pending',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
