# Generated by Django 5.2.5 on 2026-03-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0015_delete_recentaction_house_sync_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberobligation',
            name='sync_pending',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
