# Generated by Django 5.2.5 on 2026-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0016_memberobligation_sync_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
