# Generated by Django 5.2.5 on 2026-03-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0017_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='rule_guardian_requires_details',
            field=models.BooleanField(default=True, help_text='Guardian data requires mobile number, aadhaar number, date of birth.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='rule_house_must_have_members',
            field=models.BooleanField(default=True, help_text='A house cannot be without any members.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='rule_no_duplicate_obligations',
            field=models.BooleanField(default=True, help_text='Do not allow a member in the same obligation twice.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='rule_one_guardian_per_house',
            field=models.BooleanField(default=True, help_text='All houses must have exactly one Guardian.'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='rule_track_duplicate_members',
            field=models.BooleanField(default=True, help_text='Track duplicate members using date of birth and mobile number.'),
        ),
    ]
