# Generated by Django 5.2.5 on 2026-03-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0018_appsettings_rule_guardian_requires_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='old_mahall_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
