# Generated by Django 5.2.5 on 2026-03-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0019_house_old_mahall_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='firebase_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='head_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='sync_pending',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
