# Generated by Django 5.2.5 on 2026-03-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0020_area_firebase_id_area_head_person_area_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('sync_pending', models.BooleanField(db_index=True, default=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='society.memberobligation')),
            ],
        ),
    ]
